name: wakatime

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 16 * * *"

jobs:
  update-readme:
    name: update-wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "updated: wakatime"
